{"name": "Проверка невозможности создания уже существующего пользователя", "status": "passed", "start": 1726428891878, "stop": 1726428892198, "uuid": "bdacb130-ea23-4330-94af-45ad864386ff", "historyId": "f8f60ac9afb65e854b3f4239ebf5d2b1", "testCaseId": "f8f60ac9afb65e854b3f4239ebf5d2b1", "fullName": "tests.test_create_user.TestCreateUser#test_unable_create_existed_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "zurujal-osx"}, {"name": "thread", "value": "14231-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}